name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        ghc: ['92']
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    name: Build with GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - name: Build
      run: nix build -L .#halide-haskell.ghc${{ matrix.ghc }}
